# ************************************************************
# Sequel Pro SQL dump
# Version 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: localhost (MySQL 5.5.28)
# Database: hcde_518
# Generation Time: 2013-10-27 23:43:25 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table group_assignment_2
# ------------------------------------------------------------

DROP TABLE IF EXISTS `group_assignment_2`;

CREATE TABLE `group_assignment_2` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `timestamp` varchar(255) DEFAULT NULL COMMENT 'Timestamp',
  `age` varchar(255) DEFAULT NULL COMMENT 'What is your Age?',
  `gender` varchar(255) DEFAULT NULL COMMENT 'What is your Gender?',
  `marital_status` varchar(255) DEFAULT NULL COMMENT 'What is your current Marital Status?',
  `insurance_provider` varchar(255) DEFAULT NULL COMMENT 'Who provides your Healthcare Insurance? If you don''t have Insurance please select the second last option.',
  `compare_insurance_companies` varchar(255) DEFAULT NULL COMMENT 'Do you you shop and compare health insurance companies when making your decision?',
  `current_medical_condition` varchar(255) DEFAULT NULL COMMENT 'Are you currently being treated for a medical condition?',
  `choosing_treatment_doctor` varchar(255) DEFAULT NULL COMMENT 'What things concern you while choosing healthcare treatment? [Doctor]',
  `choosing_treatment_medical_facility` varchar(255) DEFAULT NULL COMMENT 'What things concern you while choosing healthcare treatment? [Medical Facility]',
  `choosing_treatment_cost` varchar(255) DEFAULT NULL COMMENT 'What things concern you while choosing healthcare treatment? [Cost]',
  `read_doctor_reviews` varchar(255) DEFAULT NULL COMMENT 'Do you read reviews on doctors or facilities?',
  `doctor_look_for` text COMMENT 'When choosing a doctor, check all that you look for?',
  `treatment_cost_vs_quality_association` varchar(255) DEFAULT NULL COMMENT 'Do you associate treatment costs with treatment quality?',
  `cost_care_factor` varchar(255) DEFAULT NULL COMMENT 'Does cost play a deciding factor in your care treatment?',
  `current_out_of_pocket` varchar(255) DEFAULT NULL COMMENT 'Do you currently have any out of pocket medical bills you are paying on?',
  `out_of_pocket_awareness` varchar(255) DEFAULT NULL COMMENT 'Were you made aware of the (out of pocket) costs to your medical expenses, and/or provided with any methods to reasonably control your costs?',
  `treatment_cost_info` varchar(255) DEFAULT NULL COMMENT 'How do you receive information about treatment costs?',
  `interest_in_app` varchar(255) DEFAULT NULL COMMENT 'Would a method that lets you compare healthcare treatment costs be a useful resource to you?',
  `using_current_methods` varchar(255) DEFAULT NULL COMMENT 'Are you currently using or aware of any methods or services to keep track of your healthcare?',
  `primary_computing_platform` varchar(255) DEFAULT NULL COMMENT 'What type of computing platform do you primarily use?',
  `insurance_terminology` text COMMENT 'Check all the terminology that you are aware of:',
  `suggestions` text COMMENT 'Please enter any suggestions or information:',
  `current_methods_used` text COMMENT 'What service(s) you use to keep track of your healthcare costs?',
  `most_useful_features` text COMMENT 'What features in the service you find most useful?',
  `desired_features` text COMMENT 'What features do you wish for in the service?',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `group_assignment_2` WRITE;
/*!40000 ALTER TABLE `group_assignment_2` DISABLE KEYS */;

INSERT INTO `group_assignment_2` (`id`, `timestamp`, `age`, `gender`, `marital_status`, `insurance_provider`, `compare_insurance_companies`, `current_medical_condition`, `choosing_treatment_doctor`, `choosing_treatment_medical_facility`, `choosing_treatment_cost`, `read_doctor_reviews`, `doctor_look_for`, `treatment_cost_vs_quality_association`, `cost_care_factor`, `current_out_of_pocket`, `out_of_pocket_awareness`, `treatment_cost_info`, `interest_in_app`, `using_current_methods`, `primary_computing_platform`, `insurance_terminology`, `suggestions`, `current_methods_used`, `most_useful_features`, `desired_features`)
VALUES
	(1,'10/23/13 23:40','27-40','Male','Single (never married)','VA/military','No','No','4','3','4','No','Education/Colleges attended, Location to work or home, Certifications','Yes','No','No','No','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Formulary, Exclusions','','','',''),
	(2,'10/24/13 13:31','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','Yes','No','4','5','3','Yes','Education/Colleges attended, Location to work or home, Certifications, Cost','No','Yes','Yes','No','Call Insurance Company, Ask Doctor, I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(3,'10/24/13 13:33','27-40','Male','Significant Other','Employer/union (including retirement plan)','No','No','5','1','3','Yes','Location to work or home, Cost, Reviews from friends, family or community','No','Yes','No','Yes','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','Yes','Desktop/Laptop','Copayment, Premium, Outpatient, Network, Deductible','','Online banking','Accuracy','N/A'),
	(4,'10/24/13 13:37','27-40','Male','Single (never married)','Employer/union (including retirement plan)','No','No','5','3','4','Yes','Education/Colleges attended, Activities the participate in, Location to work or home, Certifications, Reviews from friends, family or community','No','No','Yes','No','I don?Ûªt. I wait until the bill arrives in the mail.','No','No','Desktop/Laptop','Premium, Outpatient, Network, Deductible','','','',''),
	(5,'10/24/13 13:38','27-40','Female','Single (never married)','Employer/union (including retirement plan)','No','Yes','4','4','3','Yes','Education/Colleges attended, Certifications, Reviews from friends, family or community','No','No','No','No','Online tools','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','','',''),
	(6,'10/24/13 14:16','27-40','Female','Single (never married)','Employer/union (including retirement plan)','No','No','4','3','4','Yes','Education/Colleges attended, Location to work or home, Certifications, Cost, Reviews from friends, family or community','No','Yes','No','No','Ask Doctor, Online tools','Yes','No','Tablet (iPad, etc.)','EOB, Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','','',''),
	(7,'10/24/13 14:26','18-26','Male','Single (never married)','Employer/union (including retirement plan)','No','No','4','3','5','No','Location to work or home, Cost','Yes','Yes','Yes','No','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Mobile App','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(8,'10/24/13 14:26','27-40','Male','Married/domestic partner','Employer/union (including retirement plan)','No','No','4','4','5','No','Location to work or home, Cost, Insurance Coverage','Yes','Yes','No','Yes','Call Insurance Company','Yes','No','Tablet (iPad, etc.)','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(9,'10/24/13 15:46','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','Yes','5','5','5','No','Location to work or home, Certifications, Reviews from friends, family or community','No','No','No','No','Ask Doctor','Yes','No','Desktop/Laptop','Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(10,'10/24/13 16:19','40-64','Male','Single (never married)','Employer/union (including retirement plan)','Yes','Yes','5','4','4','Yes','Location to work or home, Reviews from friends, family or community, Insurance plan participation','Yes','Yes','Yes','Yes','Call Insurance Company, Ask Doctor','Yes','Yes','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','Overlake OneChart','Common platform for tracking medical history and appointment calendar.','Prices and cost for services'),
	(11,'10/24/13 17:34','27-40','Female','Single (never married)','Employer/union (including retirement plan)','No','No','3','4','4','No','Location to work or home, Cost, Reviews from friends, family or community','Yes','Yes','Yes','Yes','Call Insurance Company, Online tools','Yes','Yes','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(12,'10/24/13 20:54','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','Yes','No','5','5','5','Yes','Education/Colleges attended, Location to work or home, Certifications, Reviews from friends, family or community','Yes','No','Yes','No','Call Insurance Company, Ask Doctor','Yes','Yes','Tablet (iPad, etc.)','Coinsurance, Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(13,'10/24/13 23:23','27-40','Female','Single (never married)','Employer/union (including retirement plan)','Yes','No','5','5','5','Yes','Location to work or home, Certifications, Cost, Reviews from friends, family or community','Yes','Yes','No','No','Call Insurance Company, Ask Doctor, I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','Copayment, Network, Deductible','','','',''),
	(14,'10/24/13 23:24','18-26','Male','Single (never married)','Self-insured','Yes','No','5','5','4','Yes','Education/Colleges attended, Certifications, Cost, Reviews from friends, family or community','No','No','No','Yes','Call Insurance Company, Ask Doctor, Online tools','Yes','No','All three','Coinsurance, Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(15,'10/24/13 23:39','18-26','Female','Single (never married)','Medicare','No','No','5','5','3','Yes','Education/Colleges attended, Activities the participate in, Certifications, Reviews from friends, family or community','Yes','No','No','No','Online tools','Yes','No','Mobile App','Outpatient','','','',''),
	(16,'10/25/13 0:17','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','Yes','1','1','1','Yes','Education/Colleges attended, Activities the participate in, Location to work or home, in-network provider','No','Yes','Yes','No','I don?Ûªt. I wait until the bill arrives in the mail., ask at the time I make my appointment','Yes','Yes','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','','',''),
	(17,'10/25/13 0:27','18-26','Male','Single (never married)','Self-insured','No','Yes','3','3','3','No','Education/Colleges attended, Location to work or home, Certifications, Cost','Yes','No','No','Yes','Online tools','No','Yes','Mobile App','Network','','','',''),
	(18,'10/25/13 0:28','18-26','Female','Married/domestic partner','No Insurance','Yes','No','5','4','5','Yes','Location to work or home, Cost, Reviews from friends, family or community','Yes','Yes','No','No','Ask Doctor','Yes','Yes','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(19,'10/25/13 7:40','18-26','Female','Single (never married)','Self-insured','No','No','3','3','3','No','Activities the participate in, Location to work or home, Certifications, Cost, Reviews from friends, family or community','Yes','No','No','Yes','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','Premium, Network','','','',''),
	(20,'10/25/13 9:19','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','4','3','5','Yes','Education/Colleges attended, Location to work or home, Certifications, Cost, Reviews from friends, family or community','No','Yes','No','No','Call Insurance Company, Ask Doctor, Online tools','Yes','No','Desktop/Laptop','Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(21,'10/25/13 9:47','18-26','Female','Single (never married)','Employer/union (including retirement plan)','No','No','4','3','5','No','Education/Colleges attended, Location to work or home','Yes','Yes','No','Yes','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(22,'10/25/13 9:49','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','5','4','5','Yes','Education/Colleges attended, Location to work or home, Cost, Reviews from friends, family or community','No','Yes','No','No','Call Insurance Company, Ask Doctor','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(23,'10/25/13 9:51','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','Yes','2','2','4','No','Location to work or home, Certifications, Cost, Reviews from friends, family or community','No','Yes','No','No','Call Insurance Company, Ask Doctor','Yes','No','Desktop/Laptop','Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(24,'10/25/13 9:55','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','4','1','5','No','Education/Colleges attended, Location to work or home','No','No','No','No','Call Insurance Company, Ask Doctor','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(25,'10/25/13 9:55','18-26','Female','Single (never married)','Employer/union (including retirement plan)','No','No','4','5','5','No','Certifications, Reviews from friends, family or community','Yes','No','No','No','Call Insurance Company','Yes','No','Mobile App','Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(26,'10/25/13 9:56','18-26','Female','Single (never married)','Self-insured','Yes','No','4','4','5','No','Location to work or home, Certifications, Cost, Reviews from friends, family or community','No','Yes','No','Yes','Call Insurance Company, Ask Doctor','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(27,'10/25/13 10:00','40-64','Female','Single (never married)','Employer/union (including retirement plan)','No','No','5','5','4','No','Education/Colleges attended, Location to work or home, Reviews from friends, family or community','No','Yes','Yes','No','Ask Doctor, I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Tablet (iPad, etc.)','Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(28,'10/25/13 10:00','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','Yes','No','4','5','3','Yes','Education/Colleges attended, Location to work or home, Reviews from friends, family or community','No','Yes','No','No','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','','',''),
	(29,'10/25/13 10:02','40-64','Female','Single (never married)','Employer/union (including retirement plan)','No','No','5','3','5','No','Location to work or home, Reviews from friends, family or community','No','No','No','Yes','Call Insurance Company, Online tools','Yes','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(30,'10/25/13 10:03','18-26','Female','Single (never married)','Employer/union (including retirement plan)','No','No','3','3','5','No','Location to work or home, Cost, Reviews from friends, family or community','Yes','Yes','No','No','Ask Doctor, I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Mobile App','Copayment, Premium, Outpatient, Deductible','','','',''),
	(31,'10/25/13 10:03','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','5','3','5','Yes','Location to work or home, Reviews from friends, family or community','Yes','Yes','No','Yes','Call Insurance Company, Online tools','Yes','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','','',''),
	(32,'10/25/13 10:14','27-40','Female','Single (never married)','Self-insured','Yes','No','4','4','5','No','I personally meet the doctor to determine if I am comfortable; all doctors are basically qualified. But to discuss personal medical issues I must have a rapport with the individual doctor. ','No','Yes','No','Yes','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Mobile App','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(33,'10/25/13 10:32','27-40','Female','Single (never married)','No Insurance','Yes','No','5','4','3','Yes','Activities the participate in, Certifications, Reviews from friends, family or community','No','Yes','Yes','Yes','Ask Doctor','Yes','No','Desktop/Laptop','Copayment, Premium, Outpatient, Exclusions, Deductible','','','',''),
	(34,'10/25/13 10:33','18-26','Female','Single (never married)','Employer/union (including retirement plan)','No','No','3','3','4','Yes','Education/Colleges attended, Location to work or home, Cost','No','Yes','Yes','Yes','Ask Doctor','No','No','Desktop/Laptop','Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(35,'10/25/13 11:00','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','Yes','5','1','5','Yes','Education/Colleges attended, Activities the participate in, Location to work or home, Cost, Reviews from friends, family or community','Yes','Yes','No','No','Call Insurance Company, Ask Doctor, I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Mobile App','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(36,'10/25/13 11:09','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','5','5','3','No','Education/Colleges attended, Location to work or home, Reviews from friends, family or community','No','No','No','No','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(37,'10/25/13 11:23','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','Yes','No','4','4','5','Yes','Location to work or home, Reviews from friends, family or community','No','Yes','No','Yes','Call Insurance Company, Ask Doctor','Yes','Yes','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','the insurance company\'s website','claims filed/processed/denied; balance in my health services account','list of doctors who are accepting new patients'),
	(38,'10/25/13 11:29','18-26','Female','Single (never married)','School ','No','No','5','4','4','Yes','Reviews from friends, family or community','Yes','No','No','Yes','Online tools','Yes','No','Desktop/Laptop','Copayment, Outpatient, Deductible','','','',''),
	(39,'10/25/13 11:39','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','4','4','5','No','Location to work or home, Certifications, Cost, Reviews from friends, family or community','Yes','Yes','No','No','Call Insurance Company, written material provided at work','Yes','No','Desktop/Laptop','Copayment, Premium, Outpatient, Exclusions, Deductible','','','',''),
	(40,'10/25/13 11:47','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','5','5','4','Yes','Education/Colleges attended, Activities the participate in, Location to work or home, Certifications, Reviews from friends, family or community','No','No','No','No','Call Insurance Company, Ask Doctor','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(41,'10/25/13 12:03','40-64','Female','Married/domestic partner','VA/military','No','No','4','4','2','No','Location to work or home','No','No','No','Yes','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(42,'10/25/13 12:18','18-26','Female','Single (never married)','Employer/union (including retirement plan)','No','No','3','3','5','Yes','Education/Colleges attended, Location to work or home, Certifications, Cost, Reviews from friends, family or community','Yes','Yes','Yes','Yes','Call Insurance Company, Ask Doctor','Yes','No','Desktop/Laptop','Copayment, Premium, Deductible','','','',''),
	(43,'10/25/13 12:57','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','5','4','4','Yes','Location to work or home, Certifications, Reviews from friends, family or community','No','Yes','Yes','No','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(44,'10/25/13 15:48','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','5','5','5','Yes','Education/Colleges attended, Activities the participate in, Location to work or home, Certifications, Reviews from friends, family or community','Yes','Yes','No','No','Ask Doctor','Yes','No','Desktop/Laptop','Copayment, Premium, Network, Deductible','','','',''),
	(45,'10/25/13 15:59','27-40','Female','Single (never married)','Employer/union (including retirement plan)','No','No','5','4','5','Yes','Reviews from friends, family or community','No','Yes','No','No','Call Insurance Company, Ask Doctor','Yes','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','','',''),
	(46,'10/25/13 19:01','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','Yes','No','3','5','4','No','Location to work or home, Certifications, Cost','Yes','Yes','No','No','Ask Doctor','Yes','No','Desktop/Laptop','Premium, Outpatient, Network, Deductible','','','',''),
	(47,'10/25/13 19:48','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','5','5','5','Yes','Certifications, Reviews from friends, family or community','Yes','Yes','No','Yes','Ask Doctor, Online tools, Depends on what care I am seeking','Yes','Yes','Tablet (iPad, etc.)','EOB, Coinsurance, Copayment, Premium, Outpatient, Formulary, Network, Exclusions, Deductible','','My Regence .com','Reviews. Costs. Compare facilities. ','Unsure'),
	(48,'10/25/13 19:53','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','Yes','5','5','4','Yes','Location to work or home','No','Yes','No','No','Ask Doctor','Yes','No','Desktop/Laptop','Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(49,'10/25/13 20:12','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','Yes','No','5','5','3','Yes','Education/Colleges attended, Activities the participate in, Cost','No','Yes','No','Yes','if its major - I ask in advance','Yes','No','Desktop/Laptop','Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(50,'10/25/13 20:44','40-64','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','3','3','3','No','Location to work or home, in plan','No','No','No','No','I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(51,'10/25/13 21:38','18-26','Female','Single (never married)','Employer/union (including retirement plan)','No','No','4','3','3','Yes','Location to work or home, Certifications, Reviews from friends, family or community','No','Yes','No','No','Call Insurance Company','Yes','Yes','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Deductible','','Health net.com','Doctors in network ',''),
	(52,'10/26/13 13:14','27-40','Female','Married/domestic partner','Employer/union (including retirement plan)','No','No','1','2','4','Yes','Location to work or home, Cost, Reviews from friends, family or community','Yes','No','No','No','Call Insurance Company, Ask Doctor, Online tools','Yes','No','Mobile App','Coinsurance, Copayment, Premium, Outpatient, Network, Deductible','','','',''),
	(53,'10/26/13 14:29','18-26','Female','Single (never married)','Employer/union (including retirement plan)','No','No','4','4','3','No','Location to work or home, Cost, Reviews from friends, family or community','Yes','No','No','No','Ask Doctor, Online tools','No','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',''),
	(54,'10/27/13 12:14','18-26','Female','Single (never married)','Medicare','Yes','Yes','4','4','5','Yes','Education/Colleges attended, Activities the participate in, Location to work or home, Certifications, Cost, Reviews from friends, family or community','No','Yes','No','No','Call Insurance Company','Yes','Yes','Desktop/Laptop','Copayment','','Bill from insurance company','Cost info',''),
	(55,'10/27/13 13:50','27-40','Male','Single (never married)','University','Yes','No','1','1','5','No','Location to work or home, Cost, Reviews from friends, family or community','No','Yes','Yes','Yes','Online tools, I don?Ûªt. I wait until the bill arrives in the mail.','Yes','No','Desktop/Laptop','EOB, Coinsurance, Copayment, Premium, Outpatient, Network, Exclusions, Deductible','','','',NULL);

/*!40000 ALTER TABLE `group_assignment_2` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
